#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sphinx-autobuild
Version  : 2021.3.14
Release  : 1
URL      : https://files.pythonhosted.org/packages/df/a5/2ed1b81e398bc14533743be41bf0ceaa49d671675f131c4d9ce74897c9c1/sphinx-autobuild-2021.3.14.tar.gz
Source0  : https://files.pythonhosted.org/packages/df/a5/2ed1b81e398bc14533743be41bf0ceaa49d671675f131c4d9ce74897c9c1/sphinx-autobuild-2021.3.14.tar.gz
Summary  : Rebuild Sphinx documentation on changes, with live-reload in the browser.
Group    : Development/Tools
License  : MIT
Requires: sphinx-autobuild-license = %{version}-%{release}
Requires: sphinx-autobuild-python = %{version}-%{release}
Requires: sphinx-autobuild-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)

%description
# sphinx-autobuild
Rebuild Sphinx documentation on changes, with live-reload in the browser.

%package license
Summary: license components for the sphinx-autobuild package.
Group: Default

%description license
license components for the sphinx-autobuild package.


%package python
Summary: python components for the sphinx-autobuild package.
Group: Default
Requires: sphinx-autobuild-python3 = %{version}-%{release}

%description python
python components for the sphinx-autobuild package.


%package python3
Summary: python3 components for the sphinx-autobuild package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_autobuild)
Requires: pypi(colorama)
Requires: pypi(livereload)
Requires: pypi(sphinx)

%description python3
python3 components for the sphinx-autobuild package.


%prep
%setup -q -n sphinx-autobuild-2021.3.14
cd %{_builddir}/sphinx-autobuild-2021.3.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637339504
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sphinx-autobuild
cp %{_builddir}/sphinx-autobuild-2021.3.14/LICENSE %{buildroot}/usr/share/package-licenses/sphinx-autobuild/8093604dc0459c72dacab07a5a862b89708940d2
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sphinx-autobuild/8093604dc0459c72dacab07a5a862b89708940d2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
